version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: property_postgres
    environment:
      - POSTGRES_DB=property_db
      - POSTGRES_USER=property_user
      - POSTGRES_PASSWORD=property_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_data
    ports:
      - "6379:6379"

volumes:
  postgres_data: